# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - package: "myst_parser"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

